name: venv
channels:
  - conda-forge
  - pytorch

dependencies:
  # core
  - python==3.6.*
  - pytorch==1.4.0
  # utils
  - torchvision==0.5.0
  - opencv==4.2.0
  # test
  - pytest==5.1.2
  - pip:
    - --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0
    - nvidia-dali>=0.20.0
    - kornia>=0.2.0
